site_name: Calenvite
theme: readthedocs
docs_dir: 'docs'
repo_url: https://github.com/gdi3d/calenvite
site_url: https://gdi3d.github.io/calenvite

nav:
  - Home: index.md
  - Installation: Installation.md
  - Healtcheck Endpoint: api-healtcheck.md
  - Invite Endpoint: api-invite.md