site_name: Calenvite
theme: readthedocs
docs_dir: 'docs'
repo_url: https://github.com/gdi3d/calenvite
site_url: https://gdi3d.github.io/calenvite

pages:
- ['index.md', 'Home']
- ['Installation.md', Installation']
- ['api-healtcheck.md', 'API', 'Healthcheck']
- ['api-invite.md', 'API', 'Invite']